"""网页和示例共用的预设数据。"""

from __future__ import annotations

from typing import Any

PRESETS: dict[str, dict[str, Any]] = {
    "sentiment": {
        "id": "sentiment",
        "name": "情感组合图",
        "kind": "combo",
        "theme": "academic",
        "title": "",
        "bar_mode": "percent",
        "show_counts": True,
        "y2_lim": [0, 1],
        "categories": ["人物", "叙述角度", "情节"],
        "series": {"neg": [187, 3, 84], "neu": [12, 0, 9], "pos": [409, 184, 301]},
        "lines": {"pos_average": [0.63, 0.91, 0.79], "neg_average": [0.37, 0.09, 0.21]},
    },
    "sales": {
        "id": "sales",
        "name": "季度销量",
        "kind": "bar",
        "theme": "colorful",
        "title": "季度销量对比",
        "ylabel": "销量",
        "bar_mode": "grouped",
        "categories": ["一季度", "二季度", "三季度", "四季度"],
        "series": {"产品A": [32, 40, 38, 51], "产品B": [22, 28, 35, 30], "产品C": [14, 18, 16, 24]},
    },
    "line": {
        "id": "line",
        "name": "月度完成率",
        "kind": "line",
        "theme": "business",
        "title": "月度完成率",
        "y_lim": [0.5, 1.0],
        "line_label_fmt": "{:.2f}",
        "categories": ["1月", "2月", "3月", "4月", "5月", "6月"],
        "series": {
            "完成率": [0.62, 0.68, 0.71, 0.77, 0.80, 0.86],
            "目标": [0.70, 0.70, 0.72, 0.75, 0.78, 0.80],
        },
    },
    "donut": {
        "id": "donut",
        "name": "情感占比",
        "kind": "donut",
        "theme": "pastel",
        "title": "整体情感占比",
        "categories": ["正面", "中性", "负面"],
        "series": {"值": [694, 21, 274]},
    },
    "radar": {
        "id": "radar",
        "name": "作品雷达",
        "kind": "radar",
        "theme": "colorful",
        "title": "作品维度对比",
        "y_lim": [0, 1],
        "categories": ["人物", "情节", "语言", "结构", "主题"],
        "series": {"作品A": [0.82, 0.76, 0.69, 0.74, 0.88], "作品B": [0.70, 0.84, 0.80, 0.66, 0.72]},
    },
    "heatmap": {
        "id": "heatmap",
        "name": "情感热力",
        "kind": "heatmap",
        "theme": "paper",
        "title": "情感频数热力图",
        "categories": ["neg", "neu", "pos"],
        "series": {"人物": [187, 12, 409], "叙述角度": [3, 0, 184], "情节": [84, 9, 301]},
    },
    "waterfall": {
        "id": "waterfall",
        "name": "用户瀑布",
        "kind": "waterfall",
        "theme": "business",
        "title": "用户增减拆解",
        "categories": ["期初", "新增", "回流", "流失", "期末"],
        "series": {"变动": [120, 45, 18, -32, 151]},
    },
    "funnel": {
        "id": "funnel",
        "name": "转化漏斗",
        "kind": "funnel",
        "theme": "colorful",
        "title": "转化漏斗",
        "categories": ["访问", "注册", "试用", "付费"],
        "series": {"漏斗": [1200, 540, 210, 86]},
    },
    "gauge": {
        "id": "gauge",
        "name": "综合得分",
        "kind": "gauge",
        "theme": "business",
        "title": "综合得分",
        "series": {"值": [79]},
        "y_lim": [0, 100],
    },
    "area": {
        "id": "area",
        "name": "一周趋势",
        "kind": "area",
        "theme": "pastel",
        "title": "一周情感趋势",
        "bar_mode": "stacked",
        "categories": ["周一", "周二", "周三", "周四", "周五"],
        "series": {"正面": [40, 48, 52, 47, 60], "负面": [18, 15, 20, 16, 12]},
    },
    "hbar": {
        "id": "hbar",
        "name": "评述数量",
        "kind": "hbar",
        "theme": "academic",
        "title": "各维度评述数量",
        "categories": ["人物", "叙述角度", "情节"],
        "series": {"数量": [608, 187, 394]},
    },
    "pie": {
        "id": "pie",
        "name": "情感饼图",
        "kind": "pie",
        "theme": "pastel",
        "title": "整体情感占比",
        "categories": ["正面", "中性", "负面"],
        "series": {"值": [694, 21, 274]},
    },
    "scatter": {
        "id": "scatter",
        "name": "散点分布",
        "kind": "scatter",
        "theme": "colorful",
        "title": "正负分对照",
        "series": {"x": [0.2, 0.35, 0.5, 0.62, 0.7, 0.81], "y": [0.78, 0.66, 0.55, 0.4, 0.32, 0.2]},
    },
    "box": {
        "id": "box",
        "name": "分数箱线",
        "kind": "box",
        "theme": "paper",
        "title": "各维度分数分布",
        "series": {
            "人物": [0.42, 0.55, 0.61, 0.70, 0.80, 0.88],
            "情节": [0.50, 0.58, 0.66, 0.72, 0.79, 0.85],
            "语言": [0.38, 0.47, 0.60, 0.68, 0.74, 0.81],
        },
    },
    "histogram": {
        "id": "histogram",
        "name": "分数分布",
        "kind": "histogram",
        "theme": "paper",
        "title": "正面分分布",
        "bins": 8,
        "series": {"正面分": [0.62, 0.71, 0.80, 0.74, 0.88, 0.91, 0.67, 0.83, 0.77, 0.69]},
    },
}

TYPE_LABELS = {
    "bar": "柱状图",
    "hbar": "条形图",
    "line": "折线图",
    "area": "面积图",
    "combo": "组合图",
    "pie": "饼图",
    "donut": "环形图",
    "scatter": "散点图",
    "radar": "雷达图",
    "heatmap": "热力图",
    "box": "箱线图",
    "histogram": "直方图",
    "waterfall": "瀑布图",
    "funnel": "漏斗图",
    "gauge": "仪表盘",
}

THEME_LABELS = {
    "academic": "学术",
    "paper": "论文",
    "colorful": "彩色",
    "pastel": "柔和",
    "dark": "深色",
    "business": "商务",
}

TYPE_HINTS = {
    "bar": "分组或堆叠柱状图",
    "hbar": "横向条形图",
    "line": "折线趋势",
    "area": "面积/堆叠面积",
    "combo": "百分比柱 + 双轴折线",
    "pie": "饼图占比",
    "donut": "环形占比",
    "scatter": "散点对照，需要 x/y 系列",
    "radar": "多维雷达图",
    "heatmap": "行列热力",
    "box": "每组一串原始分数",
    "histogram": "原始分数分布",
    "waterfall": "期初到期末拆解",
    "funnel": "转化漏斗",
    "gauge": "单个得分仪表盘",
}
